name: 'Create a PR based on validation'

on: 
    workflow_dispatch: {} 

jobs:
  repolinter-action:
    runs-on: ubuntu-latest
    name: Run Repolinter
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: 'Run Repolinter'
        uses: DSACMS/repolinter-action@main
        with:
          output_type: 'issue'
          token: ${{ secrets.REPOLINTER_AUTO_TOKEN}}
          # The PAT needs full `repo` scope